import './globals.css';
import type { Metadata } from 'next';
import { ThemeProvider } from '@/components/ThemeProviders';
import { Inter } from 'next/font/google';
import Header from '@/components/Header';
import { cn } from '@/lib/utils';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

// const fontHeading = localFont({
//   src: '../public/fonts/Aeonik/AeonikTRIAL-Regular.otf',
//   variable: '--font-heading',
// });
// const body = localFont({
//   src: '../public/fonts/Aeonik/AeonikTRIAL-Regular.otf',
//   variable: '--body',
// });

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en' suppressHydrationWarning className='dark antialiased'>
      <head />
      <body className={cn(' min-h-screen', inter.className)}>
        <ThemeProvider attribute='class'>
          <header className='p-4'>
            <Header />
          </header>
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
